sudo: required
language: node_js
services:
  - docker
branches:
  only:
    - master
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo ${TRAVIS_COMMIT::8} ; fi`
  - docker build -t $DOCKER_REPO:$TAG ./
  - docker push $DOCKER_REPO:$TAG
